//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System_Engineer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool nt_b {
            get {
                return ((bool)(this["nt_b"]));
            }
            set {
                this["nt_b"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool nt_b_Copy {
            get {
                return ((bool)(this["nt_b_Copy"]));
            }
            set {
                this["nt_b_Copy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool nt_b_Copy1 {
            get {
                return ((bool)(this["nt_b_Copy1"]));
            }
            set {
                this["nt_b_Copy1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool nt_b_Copy2 {
            get {
                return ((bool)(this["nt_b_Copy2"]));
            }
            set {
                this["nt_b_Copy2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool nt_b_Copy3 {
            get {
                return ((bool)(this["nt_b_Copy3"]));
            }
            set {
                this["nt_b_Copy3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool nt_b_Copy4 {
            get {
                return ((bool)(this["nt_b_Copy4"]));
            }
            set {
                this["nt_b_Copy4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool nt_b_Copy5 {
            get {
                return ((bool)(this["nt_b_Copy5"]));
            }
            set {
                this["nt_b_Copy5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool nt_b_Copy6 {
            get {
                return ((bool)(this["nt_b_Copy6"]));
            }
            set {
                this["nt_b_Copy6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool nt_b_Copy7 {
            get {
                return ((bool)(this["nt_b_Copy7"]));
            }
            set {
                this["nt_b_Copy7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b1 {
            get {
                return ((bool)(this["pt_b1"]));
            }
            set {
                this["pt_b1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b2 {
            get {
                return ((bool)(this["pt_b2"]));
            }
            set {
                this["pt_b2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b3 {
            get {
                return ((bool)(this["pt_b3"]));
            }
            set {
                this["pt_b3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b4 {
            get {
                return ((bool)(this["pt_b4"]));
            }
            set {
                this["pt_b4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b5 {
            get {
                return ((bool)(this["pt_b5"]));
            }
            set {
                this["pt_b5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b6 {
            get {
                return ((bool)(this["pt_b6"]));
            }
            set {
                this["pt_b6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b {
            get {
                return ((bool)(this["pt_b"]));
            }
            set {
                this["pt_b"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy {
            get {
                return ((bool)(this["pt_b_Copy"]));
            }
            set {
                this["pt_b_Copy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy1 {
            get {
                return ((bool)(this["pt_b_Copy1"]));
            }
            set {
                this["pt_b_Copy1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy2 {
            get {
                return ((bool)(this["pt_b_Copy2"]));
            }
            set {
                this["pt_b_Copy2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy3 {
            get {
                return ((bool)(this["pt_b_Copy3"]));
            }
            set {
                this["pt_b_Copy3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy4 {
            get {
                return ((bool)(this["pt_b_Copy4"]));
            }
            set {
                this["pt_b_Copy4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy5 {
            get {
                return ((bool)(this["pt_b_Copy5"]));
            }
            set {
                this["pt_b_Copy5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy6 {
            get {
                return ((bool)(this["pt_b_Copy6"]));
            }
            set {
                this["pt_b_Copy6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy7 {
            get {
                return ((bool)(this["pt_b_Copy7"]));
            }
            set {
                this["pt_b_Copy7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy8 {
            get {
                return ((bool)(this["pt_b_Copy8"]));
            }
            set {
                this["pt_b_Copy8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy9 {
            get {
                return ((bool)(this["pt_b_Copy9"]));
            }
            set {
                this["pt_b_Copy9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy10 {
            get {
                return ((bool)(this["pt_b_Copy10"]));
            }
            set {
                this["pt_b_Copy10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy11 {
            get {
                return ((bool)(this["pt_b_Copy11"]));
            }
            set {
                this["pt_b_Copy11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy12 {
            get {
                return ((bool)(this["pt_b_Copy12"]));
            }
            set {
                this["pt_b_Copy12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy13 {
            get {
                return ((bool)(this["pt_b_Copy13"]));
            }
            set {
                this["pt_b_Copy13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy14 {
            get {
                return ((bool)(this["pt_b_Copy14"]));
            }
            set {
                this["pt_b_Copy14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy15 {
            get {
                return ((bool)(this["pt_b_Copy15"]));
            }
            set {
                this["pt_b_Copy15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy16 {
            get {
                return ((bool)(this["pt_b_Copy16"]));
            }
            set {
                this["pt_b_Copy16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pt_b_Copy17 {
            get {
                return ((bool)(this["pt_b_Copy17"]));
            }
            set {
                this["pt_b_Copy17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b {
            get {
                return ((bool)(this["wt_b"]));
            }
            set {
                this["wt_b"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy {
            get {
                return ((bool)(this["wt_b_Copy"]));
            }
            set {
                this["wt_b_Copy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy1 {
            get {
                return ((bool)(this["wt_b_Copy1"]));
            }
            set {
                this["wt_b_Copy1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy2 {
            get {
                return ((bool)(this["wt_b_Copy2"]));
            }
            set {
                this["wt_b_Copy2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy3 {
            get {
                return ((bool)(this["wt_b_Copy3"]));
            }
            set {
                this["wt_b_Copy3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy4 {
            get {
                return ((bool)(this["wt_b_Copy4"]));
            }
            set {
                this["wt_b_Copy4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy5 {
            get {
                return ((bool)(this["wt_b_Copy5"]));
            }
            set {
                this["wt_b_Copy5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy6 {
            get {
                return ((bool)(this["wt_b_Copy6"]));
            }
            set {
                this["wt_b_Copy6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy7 {
            get {
                return ((bool)(this["wt_b_Copy7"]));
            }
            set {
                this["wt_b_Copy7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy8 {
            get {
                return ((bool)(this["wt_b_Copy8"]));
            }
            set {
                this["wt_b_Copy8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy9 {
            get {
                return ((bool)(this["wt_b_Copy9"]));
            }
            set {
                this["wt_b_Copy9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy10 {
            get {
                return ((bool)(this["wt_b_Copy10"]));
            }
            set {
                this["wt_b_Copy10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy11 {
            get {
                return ((bool)(this["wt_b_Copy11"]));
            }
            set {
                this["wt_b_Copy11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy12 {
            get {
                return ((bool)(this["wt_b_Copy12"]));
            }
            set {
                this["wt_b_Copy12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy13 {
            get {
                return ((bool)(this["wt_b_Copy13"]));
            }
            set {
                this["wt_b_Copy13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy14 {
            get {
                return ((bool)(this["wt_b_Copy14"]));
            }
            set {
                this["wt_b_Copy14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy15 {
            get {
                return ((bool)(this["wt_b_Copy15"]));
            }
            set {
                this["wt_b_Copy15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy16 {
            get {
                return ((bool)(this["wt_b_Copy16"]));
            }
            set {
                this["wt_b_Copy16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy17 {
            get {
                return ((bool)(this["wt_b_Copy17"]));
            }
            set {
                this["wt_b_Copy17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wt_b_Copy18 {
            get {
                return ((bool)(this["wt_b_Copy18"]));
            }
            set {
                this["wt_b_Copy18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b {
            get {
                return ((bool)(this["st_b"]));
            }
            set {
                this["st_b"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy {
            get {
                return ((bool)(this["st_b_Copy"]));
            }
            set {
                this["st_b_Copy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy1 {
            get {
                return ((bool)(this["st_b_Copy1"]));
            }
            set {
                this["st_b_Copy1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy2 {
            get {
                return ((bool)(this["st_b_Copy2"]));
            }
            set {
                this["st_b_Copy2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy3 {
            get {
                return ((bool)(this["st_b_Copy3"]));
            }
            set {
                this["st_b_Copy3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy4 {
            get {
                return ((bool)(this["st_b_Copy4"]));
            }
            set {
                this["st_b_Copy4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy5 {
            get {
                return ((bool)(this["st_b_Copy5"]));
            }
            set {
                this["st_b_Copy5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy6 {
            get {
                return ((bool)(this["st_b_Copy6"]));
            }
            set {
                this["st_b_Copy6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy7 {
            get {
                return ((bool)(this["st_b_Copy7"]));
            }
            set {
                this["st_b_Copy7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy8 {
            get {
                return ((bool)(this["st_b_Copy8"]));
            }
            set {
                this["st_b_Copy8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy9 {
            get {
                return ((bool)(this["st_b_Copy9"]));
            }
            set {
                this["st_b_Copy9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy10 {
            get {
                return ((bool)(this["st_b_Copy10"]));
            }
            set {
                this["st_b_Copy10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy11 {
            get {
                return ((bool)(this["st_b_Copy11"]));
            }
            set {
                this["st_b_Copy11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy12 {
            get {
                return ((bool)(this["st_b_Copy12"]));
            }
            set {
                this["st_b_Copy12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy13 {
            get {
                return ((bool)(this["st_b_Copy13"]));
            }
            set {
                this["st_b_Copy13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy14 {
            get {
                return ((bool)(this["st_b_Copy14"]));
            }
            set {
                this["st_b_Copy14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy15 {
            get {
                return ((bool)(this["st_b_Copy15"]));
            }
            set {
                this["st_b_Copy15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy16 {
            get {
                return ((bool)(this["st_b_Copy16"]));
            }
            set {
                this["st_b_Copy16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy17 {
            get {
                return ((bool)(this["st_b_Copy17"]));
            }
            set {
                this["st_b_Copy17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy18 {
            get {
                return ((bool)(this["st_b_Copy18"]));
            }
            set {
                this["st_b_Copy18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy19 {
            get {
                return ((bool)(this["st_b_Copy19"]));
            }
            set {
                this["st_b_Copy19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy20 {
            get {
                return ((bool)(this["st_b_Copy20"]));
            }
            set {
                this["st_b_Copy20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy21 {
            get {
                return ((bool)(this["st_b_Copy21"]));
            }
            set {
                this["st_b_Copy21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy22 {
            get {
                return ((bool)(this["st_b_Copy22"]));
            }
            set {
                this["st_b_Copy22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy23 {
            get {
                return ((bool)(this["st_b_Copy23"]));
            }
            set {
                this["st_b_Copy23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy24 {
            get {
                return ((bool)(this["st_b_Copy24"]));
            }
            set {
                this["st_b_Copy24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool st_b_Copy25 {
            get {
                return ((bool)(this["st_b_Copy25"]));
            }
            set {
                this["st_b_Copy25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool at_b {
            get {
                return ((bool)(this["at_b"]));
            }
            set {
                this["at_b"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool at_b1 {
            get {
                return ((bool)(this["at_b1"]));
            }
            set {
                this["at_b1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool at_b2 {
            get {
                return ((bool)(this["at_b2"]));
            }
            set {
                this["at_b2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool at_b3 {
            get {
                return ((bool)(this["at_b3"]));
            }
            set {
                this["at_b3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool at_b4 {
            get {
                return ((bool)(this["at_b4"]));
            }
            set {
                this["at_b4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool at_b5 {
            get {
                return ((bool)(this["at_b5"]));
            }
            set {
                this["at_b5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool at_b6 {
            get {
                return ((bool)(this["at_b6"]));
            }
            set {
                this["at_b6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b {
            get {
                return ((bool)(this["mt_b"]));
            }
            set {
                this["mt_b"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy {
            get {
                return ((bool)(this["mt_b_Copy"]));
            }
            set {
                this["mt_b_Copy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy1 {
            get {
                return ((bool)(this["mt_b_Copy1"]));
            }
            set {
                this["mt_b_Copy1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy2 {
            get {
                return ((bool)(this["mt_b_Copy2"]));
            }
            set {
                this["mt_b_Copy2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy3 {
            get {
                return ((bool)(this["mt_b_Copy3"]));
            }
            set {
                this["mt_b_Copy3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy4 {
            get {
                return ((bool)(this["mt_b_Copy4"]));
            }
            set {
                this["mt_b_Copy4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy5 {
            get {
                return ((bool)(this["mt_b_Copy5"]));
            }
            set {
                this["mt_b_Copy5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy6 {
            get {
                return ((bool)(this["mt_b_Copy6"]));
            }
            set {
                this["mt_b_Copy6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy7 {
            get {
                return ((bool)(this["mt_b_Copy7"]));
            }
            set {
                this["mt_b_Copy7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy8 {
            get {
                return ((bool)(this["mt_b_Copy8"]));
            }
            set {
                this["mt_b_Copy8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy9 {
            get {
                return ((bool)(this["mt_b_Copy9"]));
            }
            set {
                this["mt_b_Copy9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy10 {
            get {
                return ((bool)(this["mt_b_Copy10"]));
            }
            set {
                this["mt_b_Copy10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy11 {
            get {
                return ((bool)(this["mt_b_Copy11"]));
            }
            set {
                this["mt_b_Copy11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy12 {
            get {
                return ((bool)(this["mt_b_Copy12"]));
            }
            set {
                this["mt_b_Copy12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy13 {
            get {
                return ((bool)(this["mt_b_Copy13"]));
            }
            set {
                this["mt_b_Copy13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy14 {
            get {
                return ((bool)(this["mt_b_Copy14"]));
            }
            set {
                this["mt_b_Copy14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy15 {
            get {
                return ((bool)(this["mt_b_Copy15"]));
            }
            set {
                this["mt_b_Copy15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy16 {
            get {
                return ((bool)(this["mt_b_Copy16"]));
            }
            set {
                this["mt_b_Copy16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy17 {
            get {
                return ((bool)(this["mt_b_Copy17"]));
            }
            set {
                this["mt_b_Copy17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mt_b_Copy18 {
            get {
                return ((bool)(this["mt_b_Copy18"]));
            }
            set {
                this["mt_b_Copy18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool usbLock {
            get {
                return ((bool)(this["usbLock"]));
            }
            set {
                this["usbLock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ck1_st {
            get {
                return ((bool)(this["ck1_st"]));
            }
            set {
                this["ck1_st"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ck2_st {
            get {
                return ((bool)(this["ck2_st"]));
            }
            set {
                this["ck2_st"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ck3_st {
            get {
                return ((bool)(this["ck3_st"]));
            }
            set {
                this["ck3_st"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ck4_st {
            get {
                return ((bool)(this["ck4_st"]));
            }
            set {
                this["ck4_st"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ck5_st {
            get {
                return ((bool)(this["ck5_st"]));
            }
            set {
                this["ck5_st"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ck6_st {
            get {
                return ((bool)(this["ck6_st"]));
            }
            set {
                this["ck6_st"] = value;
            }
        }
    }
}
